mklink /j "public\values" "..\andors-trail\AndorsTrail\res\values"
mklink /j "public\xml" "..\andors-trail\AndorsTrail\res\xml"
mklink /j "public\drawable" "..\andors-trail\AndorsTrail\res\drawable"
mklink /j "public\raw" "..\andors-trail\AndorsTrail\res\raw"
mkdir "public\dev"
mklink /j "public\dev\values" "..\andors-trail-dev\AndorsTrail\res\values"
mklink /j "public\dev\xml" "..\andors-trail-dev\AndorsTrail\res\xml"
mklink /j "public\dev\drawable" "..\andors-trail-dev\AndorsTrail\res\drawable"
mklink /j "public\dev\raw" "..\andors-trail-dev\AndorsTrail\res\raw"
pause
